---
title: "R Notebook"
output: html_notebook
---


arrays:
```{r}
num_products <- c('Tortas','zumos','Yogurt con cereal','Galletas')
num_caf <- c('Cafeteria A','Cafeteria B','Cafeteria C')
val <- c(20,22,18,10,9,12,15,15,13,17,12,10)

"we create the matrix"
matrix_price <- matrix(data = val, nrow = length(num_products),ncol = length(num_caf),byrow = TRUE,dimnames = list(num_products,num_caf) )
print(matrix_price)
```

obtaining the size of the matrix:
```{r}
dim(matrix_price)
```
cols and rows:
```{r}
col_names<-colnames(matrix_price)
row_names <-rownames(matrix_price)
print(col_names)
print(row_names)
col_names[3]
```

Operations with matrix:
```{r}
matrix_price
t(matrix_price)
```
```{r}
matrix_price + 2
matrix_price * 2
```

graphs of a matrix Matplot:
```{r}
matplot(matrix_price, type = 'o', pch=NULL,col=c('red','black','blue','orange'),xlab = 'Distintos productos',ylab = 'Valor del producto',xlim = c(1,4),ylim = c(9,25))
```

subsetting:
```{r}
sub1 <-matrix_price[c(1:3),c('Cafeteria A')]
sub2 <-matrix_price[c(2:4),c(1:3)]
print(sub1)
"---------------------------------------------------"
print(sub2)
"---------------------------------------------------"
"whithout the last caf(the C) :"
print(matrix_price[,c(-3)])
```

