---
title: "R Notebook"
output: html_notebook
---

Vectors are always of the same type, if inside a vector there are numbers and a str, the whole vector will be str

Vectors:
```{r}
vec1 <- c(1,2,3,4,5,6,7,8)
vec2 <- c(4,7,'hello',8,'hi')
vec3 <- c(TRUE,FALSE,TRUE)
vec4 <- c(1:6,88)
print(vec1)
print(vec2)
print(vec3)
print(vec4)
```

Access vector positions:
```{r}
print(vec1[5])
print(vec2[1:6])

"take from positions 2 to 4 and additionally 6"
print(vec1[c(2:4,6)])

"negative number = all the data except the indicated number"
print(vec1[-4])
print(vec1[c(-1,-3,-5,-8)])
```
For operate with vectors, must be the same size

Operations with vectors:
```{r}
vec_num1 <- c(1:5)
vec_num2 <- c(6:10)
print(vec_num1)
print(vec_num2)
"SUM"
print(vec_num1 + vec_num2)
"Substract"
print(vec_num1 - vec_num2)
"Multiplication"
print(vec_num1 * vec_num2)
"Split"
print(vec_num1 / vec_num2)
"Scalar product -> sum of all vector multiplications"
print(vec_num1 %*% vec_num2)
```
Functions:
```{r}
days_to_minutes <- function(days){
  minutes <- ((days*60)*60)
  return(paste('Total:',minutes,'m'))
}
print(days_to_minutes(10))
```

